name: Enterprise UI Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§³ Checkout Repo ğŸ§³
        uses: actions/checkout@v3
      - name: ğŸ“± Setup Node ğŸ“±
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: ğŸ§µ Install Deps ğŸ§µ
        run: npm ci
      - name: âœ¨ Prettier Check âœ¨
        run: npm run format:check

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§³ Checkout Repo ğŸ§³
        uses: actions/checkout@v3
      - name: ğŸ“± Setup Node ğŸ“±
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: ğŸ§µ Install Deps ğŸ§µ
        run: npm ci
      - name: âœ… Unit Tests âœ…
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§³ Checkout Repo ğŸ§³
        uses: actions/checkout@v3
      - name: ğŸ“± Setup Node ğŸ“±
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: ğŸ§µ Install Deps ğŸ§µ
        run: npm ci
      - name: ğŸ¡ Build Repo ğŸ¡
        run: npm run build
